DESCRIPTION="Incremental View Maintenance for materialized views"
REPO="https://github.com/sraoss/pg_ivm.git"
LICENSE="PostgreSQL"
VERSION_17="1.15"
VERSION_18="1.15"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="pg-ivm"
